# Generated by Django 2.1.4 on 2018-12-14 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wag_custom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='disqus_shortname',
            field=models.CharField(blank=True, help_text='Disqus site shortname for comments', max_length=50, null=True),
            preserve_default=False,
        ),
    ]
