# Generated by Django 2.1.5 on 2019-03-03 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wag_custom', '0002_remove_sitesettings_site_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='site_logo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
