# Generated by Django 2.1.5 on 2019-03-03 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wag_custom', '0004_auto_20190303_1929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='site_logo',
        ),
        migrations.AlterField(
            model_name='footer',
            name='contact_type',
            field=models.CharField(choices=[('fas fa-phone', 'Phone'), ('fas fa-envelope', 'Email'), ('fab fa-facebook-f', 'Facebook'), ('fab fa-instagram', 'Instagram'), ('fab fa-linkedin', 'LinkedIn'), ('fab fa-twitter', 'Twitter'), ('fab fa-pinterest', 'Pinterest'), ('fab fa-youtube', 'Youtube'), ('fab fa-github', 'GitHub'), ('fab fa-gitlab', 'GitLab')], max_length=50),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
