# Generated by Django 2.1.5 on 2019-03-03 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0021_image_file_hash'),
        ('wag_custom', '0005_auto_20190303_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='site_logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
