# Generated by Django 2.1.5 on 2019-03-09 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wag_custom', '0007_auto_20190309_1348'),
    ]

    operations = [
        migrations.RenameField(
            model_name='social',
            old_name='social_info',
            new_name='id_handle_contact',
        ),
        migrations.AddField(
            model_name='social',
            name='social_url',
            field=models.CharField(default=1, editable=False, max_length=50),
            preserve_default=False,
        ),
    ]
