# Generated by Django 2.1.5 on 2019-03-10 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wag_custom', '0008_auto_20190309_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='disqus_shortname',
            field=models.CharField(blank=True, help_text='Disqus site shortname for comments', max_length=50, null=True),
        ),
    ]
