# Generated by Django 2.1.4 on 2018-12-17 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bootstrap_grayscale', '0045_remove_footer_info_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='info_prefix',
            field=models.CharField(default='', editable=False, max_length=10),
            preserve_default=False,
        ),
    ]
