# Generated by Django 2.1.4 on 2018-12-17 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bootstrap_grayscale', '0046_footer_info_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='contact_info',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='footer',
            name='contact_type',
            field=models.CharField(choices=[('fas fa-phone', 'Phone'), ('fas fa-envelope', 'Email'), ('fab fa-facebook-f', 'Facebook'), ('fa-instagram', 'Instagram'), ('fab fa-linkedin', 'LinkedIn'), ('fab fa-twitter', 'Twitter'), ('fab fa-pinterest', 'Pinterest'), ('fab fa-github', 'GitHub'), ('fab fa-gitlab', 'GitLab')], default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='footer',
            name='copyright_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='footer',
            name='include_footer',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
