# Generated by Django 2.1.4 on 2018-12-17 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bootstrap_grayscale', '0048_auto_20181217_0219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialmediasettings',
            name='site',
        ),
        migrations.DeleteModel(
            name='SocialMediaSettings',
        ),
    ]
