# Generated by Django 2.1.4 on 2018-12-17 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bootstrap_grayscale', '0050_auto_20181217_0240'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='info_prefix',
            field=models.CharField(default='', editable=False, max_length=10),
            preserve_default=False,
        ),
    ]
