# Generated by Django 2.1.4 on 2018-12-17 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bootstrap_grayscale', '0051_contactinfo_info_prefix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactinfo',
            name='info_prefix',
        ),
    ]
