# Generated by Django 2.1.4 on 2018-12-17 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bootstrap_grayscale', '0053_admincontact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admincontact',
            name='site',
        ),
        migrations.DeleteModel(
            name='AdminContact',
        ),
    ]
