# Generated by Django 2.1.4 on 2018-12-17 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bootstrap_grayscale', '0055_auto_20181217_2349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactinfo',
            name='info_prefix',
        ),
    ]
