# Generated by Django 2.1.4 on 2018-12-18 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bootstrap_grayscale', '0058_auto_20181218_0029'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='header',
            options={},
        ),
        migrations.RemoveField(
            model_name='header',
            name='sort_order',
        ),
    ]
