# Generated by Django 2.1.4 on 2018-12-18 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0021_image_file_hash'),
        ('bootstrap_grayscale', '0059_auto_20181218_0032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='header',
            name='site_logo',
        ),
        migrations.RemoveField(
            model_name='header',
            name='site_settings',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='banner_color',
            field=models.CharField(blank=True, help_text='Fill in a hex colour value', max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Header',
        ),
    ]
