# Generated by Django 2.1.4 on 2018-12-18 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bootstrap_grayscale', '0060_auto_20181218_0041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footer',
            name='include_footer',
        ),
    ]
