# Generated by Django 2.1.4 on 2018-12-18 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bootstrap_grayscale', '0061_remove_footer_include_footer'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='include_footer',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
