# Generated by Django 2.1.4 on 2018-12-23 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bootstrap_grayscale', '0062_sitesettings_include_footer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footer',
            name='site_settings',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='site',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='site_logo',
        ),
        migrations.DeleteModel(
            name='Footer',
        ),
        migrations.DeleteModel(
            name='SiteSettings',
        ),
    ]
