# Generated by Django 2.1.5 on 2019-03-05 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0021_image_file_hash'),
        ('bootstrap_grayscale', '0067_bootstrapgrayscalepostpage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bootstrapgrayscalepostpage',
            old_name='created_data',
            new_name='created_date',
        ),
        migrations.AddField(
            model_name='bootstrapgrayscaleblogpage',
            name='header_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='bootstrapgrayscaleblogpage',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
