# Generated by Django 2.1.5 on 2019-03-05 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bootstrap_grayscale', '0068_auto_20190305_0139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bootstrapgrayscalepostpage',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='bootstrapgrayscalepostpage',
            name='modified_date',
        ),
    ]
