# Generated by Django 2.1.5 on 2019-03-05 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bootstrap_grayscale', '0069_auto_20190305_0203'),
    ]

    operations = [
        migrations.AddField(
            model_name='bootstrapgrayscalepostpage',
            name='summary',
            field=models.CharField(default='summary', help_text='Shown on Blog/News index page.', max_length=100),
            preserve_default=False,
        ),
    ]
