# Generated by Django 2.1.5 on 2019-03-05 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bootstrap_grayscale', '0070_bootstrapgrayscalepostpage_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='bootstrapgrayscalepostpage',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
