# Generated by Django 2.1.3 on 2018-11-25 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailcore', '0040_page_draft_title'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('grayscale', '0006_auto_20181124_1910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grayscalemastheadpage',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='GrayscaleMastheadPage',
        ),
    ]
