# Generated by Django 2.1.4 on 2018-12-24 01:35

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0002_auto_20181223_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footer',
            name='site_settings',
            field=modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='footer', to='utils.SiteSettings'),
        ),
    ]
