# Generated by Django 2.1.4 on 2018-12-24 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0003_auto_20181224_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='include_footer',
            field=models.BooleanField(null=True),
        ),
    ]
