# Generated by Django 2.1.4 on 2018-12-24 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0004_auto_20181224_0137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='site',
        ),
    ]
