# Generated by Django 2.1.4 on 2018-12-24 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('utils', '0005_remove_sitesettings_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='site',
            field=models.OneToOneField(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site'),
            preserve_default=False,
        ),
    ]
