# Generated by Django 2.1.5 on 2019-03-04 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailmenus', '0022_auto_20170913_2125'),
        ('wagtailcore', '0040_page_draft_title'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('bootstrap_blog', '0004_auto_20190304_0148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bootstrapblogpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='bootstrappostpage',
            name='header_image',
        ),
        migrations.RemoveField(
            model_name='bootstrappostpage',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='BootstrapBlogPage',
        ),
        migrations.DeleteModel(
            name='BootstrapPostPage',
        ),
    ]
